/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as HealthRouteImport } from './routes/health'
import { Route as MembersRouteImport } from './routes/members'
import { Route as InternalPollRouteImport } from './routes/internal.poll'
import { Route as MemberIdRouteImport } from './routes/member.$id'
import { Route as TickerSymRouteImport } from './routes/ticker.$sym'
import { Route as TradeIdRouteImport } from './routes/trade.$id'
import { Route as ApiPushSubscribeRouteImport } from './routes/api.push.subscribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalPollRoute = InternalPollRouteImport.update({
  id: '/internal/poll',
  path: '/internal/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIdRoute = MemberIdRouteImport.update({
  id: '/member/$id',
  path: '/member/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TickerSymRoute = TickerSymRouteImport.update({
  id: '/ticker/$sym',
  path: '/ticker/$sym',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeIdRoute = TradeIdRouteImport.update({
  id: '/trade/$id',
  path: '/trade/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSubscribeRoute = ApiPushSubscribeRouteImport.update({
  id: '/api/push/subscribe',
  path: '/api/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/health': typeof HealthRoute
  '/members': typeof MembersRoute
  '/internal/poll': typeof InternalPollRoute
  '/member/$id': typeof MemberIdRoute
  '/ticker/$sym': typeof TickerSymRoute
  '/trade/$id': typeof TradeIdRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/health': typeof HealthRoute
  '/members': typeof MembersRoute
  '/internal/poll': typeof InternalPollRoute
  '/member/$id': typeof MemberIdRoute
  '/ticker/$sym': typeof TickerSymRoute
  '/trade/$id': typeof TradeIdRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/health': typeof HealthRoute
  '/members': typeof MembersRoute
  '/internal/poll': typeof InternalPollRoute
  '/member/$id': typeof MemberIdRoute
  '/ticker/$sym': typeof TickerSymRoute
  '/trade/$id': typeof TradeIdRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/alerts'
    | '/health'
    | '/members'
    | '/internal/poll'
    | '/member/$id'
    | '/ticker/$sym'
    | '/trade/$id'
    | '/api/push/subscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alerts'
    | '/health'
    | '/members'
    | '/internal/poll'
    | '/member/$id'
    | '/ticker/$sym'
    | '/trade/$id'
    | '/api/push/subscribe'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/alerts'
    | '/health'
    | '/members'
    | '/internal/poll'
    | '/member/$id'
    | '/ticker/$sym'
    | '/trade/$id'
    | '/api/push/subscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AlertsRoute: typeof AlertsRoute
  HealthRoute: typeof HealthRoute
  MembersRoute: typeof MembersRoute
  InternalPollRoute: typeof InternalPollRoute
  MemberIdRoute: typeof MemberIdRoute
  TickerSymRoute: typeof TickerSymRoute
  TradeIdRoute: typeof TradeIdRoute
  ApiPushSubscribeRoute: typeof ApiPushSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/poll': {
      id: '/internal/poll'
      path: '/internal/poll'
      fullPath: '/internal/poll'
      preLoaderRoute: typeof InternalPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/$id': {
      id: '/member/$id'
      path: '/member/$id'
      fullPath: '/member/$id'
      preLoaderRoute: typeof MemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticker/$sym': {
      id: '/ticker/$sym'
      path: '/ticker/$sym'
      fullPath: '/ticker/$sym'
      preLoaderRoute: typeof TickerSymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/$id': {
      id: '/trade/$id'
      path: '/trade/$id'
      fullPath: '/trade/$id'
      preLoaderRoute: typeof TradeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/subscribe': {
      id: '/api/push/subscribe'
      path: '/api/push/subscribe'
      fullPath: '/api/push/subscribe'
      preLoaderRoute: typeof ApiPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AlertsRoute: AlertsRoute,
  HealthRoute: HealthRoute,
  MembersRoute: MembersRoute,
  InternalPollRoute: InternalPollRoute,
  MemberIdRoute: MemberIdRoute,
  TickerSymRoute: TickerSymRoute,
  TradeIdRoute: TradeIdRoute,
  ApiPushSubscribeRoute: ApiPushSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
